<?php

/**
 * @file
 * Main bootstrap file of the single_profile_tools module.
 */

/**
 * Implements hook_menu().
 *
 */
function single_profile_tools_menu() {
  $menu = array();

  $menu['single_profile_tools/example'] = array(
    'title' => 'TIC test stuff',
    'description' => 'Test single_profile_tools stuff and such',
    'page callback' => 'single_profile_tools_test_stuff',
    'access arguments' => array('access administration pages'),
    'file' => 'single_profile_tools.pages.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
  );

  return $menu;
}

/**
 * Implements of hook_services_resources().
 */
function single_profile_tools_services_resources() {
  $api = array(
    'blog' => array(
      'operations' => array(
        'retrieve' => array(
          'help' => 'Retrieves posted blogs',
          'callback' => '_single_profile_tools_blog_retrieve',
          'access callback' => 'user_access',
          'access arguments' => array('access content'),
          'access arguments append' => FALSE,
          'args' => array(
            array(
              'name' => 'fn',
              'type' => 'string',
              'description' => 'Function to perform',
              'source' => array('path' => '0'),
              'optional' => TRUE,
              'default' => '0',
            ),
            array(
              'name' => 'nitems',
              'type' => 'int',
              'description' => 'Number of latest items to get',
              'source' => array('param' => 'nitems'),
              'optional' => TRUE,
              'default' => '0',
            ),
            array(
              'name' => 'since',
              'type' => 'int',
              'description' => 'Posts from the last number of days',
              'source' => array('param' => 'since'),
              'optional' => TRUE,
              'default' => '0',
            ),
          ),
        ),
      ),
    ),
  );

  return $api;
}

/**
 * Callback function for blog retrieve
 */
function _single_profile_tools_blog_retrieve($fn, $nitems, $timestamp) {
  // Check for mad values
  $nitems = intval($nitems);
  $timestamp = intval($timestamp);

  return single_profile_tools_find_blog_items($nitems, $timestamp);
}

/**
 * Gets blog posts
 */
function single_profile_tools_find_blog_items($nitems, $timestamp) {
  // Compose query
  $query = db_select('node', 'n');
  $query->join('node_revision', 'v', '(n.nid = v.nid) AND (n.vid = v.vid)');
  $query->join('users', 'u', 'n.uid = u.uid');
  $query->join('field_data_body', 'b', '((b.entity_type = \'node\') AND (b.entity_id = n.nid) AND (b.revision_id = n.vid))');
  $query->fields('v', array('timestamp', 'title'));
  $query->addField('u', 'name', 'author');
  $query->addField('b', 'body_value', 'content');
  $query->condition('n.type', 'arsingle_profile_toolsle', '=');
  // How many days ago?
  if ($timestamp) {
    $query->condition('v.timestamp', time() - ($timestamp * 60 * 60 * 24), '>');
  }
  $query->orderBy('v.timestamp', 'DESC');
  // Limited by items?
  if ($nitems) {
    $query->range(0, $nitems);
  }
  $items = $query->execute()->fetchAll();

  return $items;
}

function single_profile_tools_services_request_postprocess_alter($controller, $args, &$result) {
//  unset($result['some_kind_of_field']);
}

function single_profile_taxonomy_terms_delete($vocab_machine_name) {
  $vocab = taxonomy_vocabulary_machine_name_load($vocab_machine_name);
  if ($vocab) {
    $query = new EntityFieldQuery();
    $result = $query
        ->entityCondition('entity_type', 'taxonomy_term')
        ->propertyCondition('vid', $vocab->vid)
        ->execute();
    foreach ($result['taxonomy_term'] as $term) {
      taxonomy_term_delete($term->tid);
    }
  }
}

/**
 * Implements hook_migrate_api().
 */
function single_profile_tools_migrate_api() {
  $api = array(
    'api' => 2,
    'migrations' => array(
      'Newsletters' => array('class_name' => 'NewslettersMigration'),
      'Countries' => array('class_name' => 'CountriesMigration'),
    ),
  );
  return $api;
}

/**
 * Returns Drupal entity ID by matching a custom field value.
 * 
 * Usefull to fetch drupal ID from entity that was imported from external
 * source and that carries the external source ID
 * 
 * @param string $entity_type
 * @param string $bundle
 * @param string $field_name
 * @param string $value
 */
function single_profile_tools_entity_id_from_field_value($entity_type, $bundle, $field_name, $value) {
  if (isset($entity_type, $bundle, $field_name, $value)) {
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', $entity_type)
        ->entityCondition('bundle', $bundle)
        ->fieldCondition($field_name, 'value', $value); // TODO only works with text fields?
    $result = $query->execute();
    if (isset($result[$entity_type])) {
      $entity_ids = array_keys($result[$entity_type]);
      $entity_id = reset($entity_ids);   // TODO better way dealing with multiple ids
      return $entity_id;
    }
    else {
      watchdog('notice', 'no entity found that matches the field value');
    }
  }
  else {
    watchdog('error', 'cannot look up entity id because of missing parameters');
  }
}
