<?php

/**
 * @file tic.module
 * TODO: Enter file description here.
 */

/**
 * Implements hook_menu().
 */
function tic_menu() {
  $items['tic/example'] = array(
    'title' => 'Example interaction with service',
    'page callback' => 'tic_example',
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );

  $items['tic/test1'] = array(
    'title' => 'test MsDynamicsPHP',
    'page callback' => 'tic_test1',
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );

  $items['tic/test2'] = array(
    'title' => 'test CRMOnlinefromPHP',
    'page callback' => 'tic_test2',
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );

  $items['tic/test3'] = array(
    'title' => 'test 6dg Dynamics CRM PHP Connector',
    'page callback' => 'tic_test3',
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );

  $items['tic/test4'] = array(
    'title' => 'test Dynamics CRM 2011 Connector for PHP',
    'page callback' => 'tic_test4',
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );

  $items['tic/test5'] = array(
    'title' => 'test PHP Dynamics Online CRM 2011 SOAP Class',
    'page callback' => 'tic_test5',
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );

  $items['tic/test6'] = array(
    'title' => 'test MS lab',
    'page callback' => 'tic_test6',
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );

  $items['admin/config/system/profile_client'] = array(
    'title' => 'Profile client',
    'description' => 'Configuration for profile client',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
    'weight' => '0',
  );

  $items['admin/config/system/profile_client/settings'] = array(
    'title' => 'Profile client configuration settings',
    'description' => 'Settings for profile client',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('profile_client_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'tic.forms.inc',
  );

  return $items;
}


/**
 * test MSDynamicsPHP. 
 * http://mscrmtools.blogspot.com/2012/08/php-to-crm-online-easy-way-to-do.html?showComment=1377215219071#c4499748507793030702
 * @return string
 */
function tic_test1() {
  require_once('MSDynamicsPHP/index.php');
  return 'testing MSDynamicsPHP';
}

/** 
 * example page
 * @return string
 */
function tic_example() {
  return 'crming';
}

/**
 * test CRMOnlinefromPHP
 * official MS with modifs from http://mscrmtools.blogspot.com/2012/08/php-to-crm-online-easy-way-to-do.html
 * @return string
 */
function tic_test2() {
  require_once('CRMOnlinefromPHP/Source/end/PHP2CRMOnline/Main.php');
  return 'testing CRMOnlinefromPHP';
}

/**
 * test 6dg Dynamics CRM PHP Connector
 * https://bitbucket.org/6dg/dynamics-crm-php-connector
 * @return string
 */
function tic_test3() {
  require_once('dynamics-crm-php-connector/index.php');
  return 'test 6dg Dynamics CRM PHP Connector';
}

//

/**
 * test Dynamics CRM 2011 Connector for PHP
 * https://bitbucket.org/6dg/dynamics-crm-php-connector
 * @return string
 */
function tic_test4() {
  require_once('php-dynamics-crm-2011/DynamicsCRM2011.demo.php');
  return 'test Dynamics CRM 2011 Connector for PHP';
}
/**
 * PHP Dynamics Online CRM 2011 SOAP Class
 * https://github.com/Ben-Speakman/PHP-Dynamics-Online-CRM-2011-SOAP-Class
 * @return string
 */

function tic_test5() {
  require_once('PHP-Dynamics-Online-CRM-2011-SOAP-Class/index.php');
  return 'test PHP Dynamics Online CRM 2011 SOAP Class';
}

/**
 * MS Lab from docs
 * @return string
 */

function tic_test6() {
  require_once('PHP2CRMOnline/Main.php');


return 'test lab from docs';
}

